//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.16 at 04:05:57 PM CEST 
//


package com.fl.massengineprocessor.ws.skeleton;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fl.massengineprocessor.ws.skeleton package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetTaskItemsDetails_QNAME = new QName("tns", "getTaskItemsDetails");
    private final static QName _GetTaskItemsDetailsResponse_QNAME = new QName("tns", "getTaskItemsDetailsResponse");
    private final static QName _UpDateTaskItems_QNAME = new QName("tns", "upDateTaskItems");
    private final static QName _UpDateTaskItemsResponse_QNAME = new QName("tns", "upDateTaskItemsResponse");
    private final static QName _TaskItem_QNAME = new QName("service.views", "TaskItem");
    private final static QName _TaskItemCoId_QNAME = new QName("service.views", "co_id");
    private final static QName _TaskItemUpdatedAt_QNAME = new QName("service.views", "updated_at");
    private final static QName _TaskItemProcessDate_QNAME = new QName("service.views", "process_date");
    private final static QName _TaskItemFailureReason_QNAME = new QName("service.views", "failure_reason");
    private final static QName _TaskItemParametersDebitValue_QNAME = new QName("service.views", "parameters_debit_value");
    private final static QName _TaskItemCustumerExernalId_QNAME = new QName("service.views", "custumer_exernal_id");
    private final static QName _TaskItemGmdRequestId_QNAME = new QName("service.views", "gmd_request_id");
    private final static QName _TaskItemGmdReauestStatus_QNAME = new QName("service.views", "gmd_reauest_status");
    private final static QName _TaskItemImsi_QNAME = new QName("service.views", "imsi");
    private final static QName _TaskItemStatus_QNAME = new QName("service.views", "status");
    private final static QName _TaskItemMsisdn_QNAME = new QName("service.views", "msisdn");
    private final static QName _TaskItemTaskItemsMarket_QNAME = new QName("service.views", "task_items_market");
    private final static QName _TaskItemRatePlan_QNAME = new QName("service.views", "rate_plan");
    private final static QName _TaskItemMaapTask_QNAME = new QName("service.views", "maap_task");
    private final static QName _TaskItemCreatedAt_QNAME = new QName("service.views", "created_at");
    private final static QName _TaskItemErrorMessage_QNAME = new QName("service.views", "error_message");
    private final static QName _TaskItemFormule_QNAME = new QName("service.views", "formule");
    private final static QName _TaskItemParametersDurationValue_QNAME = new QName("service.views", "parameters_duration_value");
    private final static QName _TaskItemFullname_QNAME = new QName("service.views", "fullname");
    private final static QName _UpDateTaskItemsResponseUpDateTaskItemsResult_QNAME = new QName("tns", "upDateTaskItemsResult");
    private final static QName _UpDateTaskItemsNd_QNAME = new QName("tns", "nd");
    private final static QName _UpDateTaskItemsStatus_QNAME = new QName("tns", "status");
    private final static QName _UpDateTaskItemsGmdRequestId_QNAME = new QName("tns", "gmd_request_id");
    private final static QName _GetTaskItemsDetailsResponseGetTaskItemsDetailsResult_QNAME = new QName("tns", "getTaskItemsDetailsResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fl.massengineprocessor.ws.skeleton
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTaskItemsDetails }
     * 
     */
    public GetTaskItemsDetails createGetTaskItemsDetails() {
        return new GetTaskItemsDetails();
    }

    /**
     * Create an instance of {@link GetTaskItemsDetailsResponse }
     * 
     */
    public GetTaskItemsDetailsResponse createGetTaskItemsDetailsResponse() {
        return new GetTaskItemsDetailsResponse();
    }

    /**
     * Create an instance of {@link UpDateTaskItems }
     * 
     */
    public UpDateTaskItems createUpDateTaskItems() {
        return new UpDateTaskItems();
    }

    /**
     * Create an instance of {@link UpDateTaskItemsResponse }
     * 
     */
    public UpDateTaskItemsResponse createUpDateTaskItemsResponse() {
        return new UpDateTaskItemsResponse();
    }

    /**
     * Create an instance of {@link TaskItem }
     * 
     */
    public TaskItem createTaskItem() {
        return new TaskItem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTaskItemsDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tns", name = "getTaskItemsDetails")
    public JAXBElement<GetTaskItemsDetails> createGetTaskItemsDetails(GetTaskItemsDetails value) {
        return new JAXBElement<GetTaskItemsDetails>(_GetTaskItemsDetails_QNAME, GetTaskItemsDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTaskItemsDetailsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tns", name = "getTaskItemsDetailsResponse")
    public JAXBElement<GetTaskItemsDetailsResponse> createGetTaskItemsDetailsResponse(GetTaskItemsDetailsResponse value) {
        return new JAXBElement<GetTaskItemsDetailsResponse>(_GetTaskItemsDetailsResponse_QNAME, GetTaskItemsDetailsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpDateTaskItems }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tns", name = "upDateTaskItems")
    public JAXBElement<UpDateTaskItems> createUpDateTaskItems(UpDateTaskItems value) {
        return new JAXBElement<UpDateTaskItems>(_UpDateTaskItems_QNAME, UpDateTaskItems.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpDateTaskItemsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tns", name = "upDateTaskItemsResponse")
    public JAXBElement<UpDateTaskItemsResponse> createUpDateTaskItemsResponse(UpDateTaskItemsResponse value) {
        return new JAXBElement<UpDateTaskItemsResponse>(_UpDateTaskItemsResponse_QNAME, UpDateTaskItemsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaskItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "TaskItem")
    public JAXBElement<TaskItem> createTaskItem(TaskItem value) {
        return new JAXBElement<TaskItem>(_TaskItem_QNAME, TaskItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "co_id", scope = TaskItem.class)
    public JAXBElement<BigInteger> createTaskItemCoId(BigInteger value) {
        return new JAXBElement<BigInteger>(_TaskItemCoId_QNAME, BigInteger.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "updated_at", scope = TaskItem.class)
    public JAXBElement<XMLGregorianCalendar> createTaskItemUpdatedAt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TaskItemUpdatedAt_QNAME, XMLGregorianCalendar.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "process_date", scope = TaskItem.class)
    public JAXBElement<XMLGregorianCalendar> createTaskItemProcessDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TaskItemProcessDate_QNAME, XMLGregorianCalendar.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "failure_reason", scope = TaskItem.class)
    public JAXBElement<String> createTaskItemFailureReason(String value) {
        return new JAXBElement<String>(_TaskItemFailureReason_QNAME, String.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "parameters_debit_value", scope = TaskItem.class)
    public JAXBElement<String> createTaskItemParametersDebitValue(String value) {
        return new JAXBElement<String>(_TaskItemParametersDebitValue_QNAME, String.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "custumer_exernal_id", scope = TaskItem.class)
    public JAXBElement<String> createTaskItemCustumerExernalId(String value) {
        return new JAXBElement<String>(_TaskItemCustumerExernalId_QNAME, String.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "gmd_request_id", scope = TaskItem.class)
    public JAXBElement<BigInteger> createTaskItemGmdRequestId(BigInteger value) {
        return new JAXBElement<BigInteger>(_TaskItemGmdRequestId_QNAME, BigInteger.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "gmd_reauest_status", scope = TaskItem.class)
    public JAXBElement<BigInteger> createTaskItemGmdReauestStatus(BigInteger value) {
        return new JAXBElement<BigInteger>(_TaskItemGmdReauestStatus_QNAME, BigInteger.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "imsi", scope = TaskItem.class)
    public JAXBElement<String> createTaskItemImsi(String value) {
        return new JAXBElement<String>(_TaskItemImsi_QNAME, String.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "status", scope = TaskItem.class)
    public JAXBElement<String> createTaskItemStatus(String value) {
        return new JAXBElement<String>(_TaskItemStatus_QNAME, String.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "msisdn", scope = TaskItem.class)
    public JAXBElement<BigInteger> createTaskItemMsisdn(BigInteger value) {
        return new JAXBElement<BigInteger>(_TaskItemMsisdn_QNAME, BigInteger.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "task_items_market", scope = TaskItem.class)
    public JAXBElement<String> createTaskItemTaskItemsMarket(String value) {
        return new JAXBElement<String>(_TaskItemTaskItemsMarket_QNAME, String.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "rate_plan", scope = TaskItem.class)
    public JAXBElement<String> createTaskItemRatePlan(String value) {
        return new JAXBElement<String>(_TaskItemRatePlan_QNAME, String.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "maap_task", scope = TaskItem.class)
    public JAXBElement<BigInteger> createTaskItemMaapTask(BigInteger value) {
        return new JAXBElement<BigInteger>(_TaskItemMaapTask_QNAME, BigInteger.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "created_at", scope = TaskItem.class)
    public JAXBElement<XMLGregorianCalendar> createTaskItemCreatedAt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TaskItemCreatedAt_QNAME, XMLGregorianCalendar.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "error_message", scope = TaskItem.class)
    public JAXBElement<String> createTaskItemErrorMessage(String value) {
        return new JAXBElement<String>(_TaskItemErrorMessage_QNAME, String.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "formule", scope = TaskItem.class)
    public JAXBElement<String> createTaskItemFormule(String value) {
        return new JAXBElement<String>(_TaskItemFormule_QNAME, String.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "parameters_duration_value", scope = TaskItem.class)
    public JAXBElement<String> createTaskItemParametersDurationValue(String value) {
        return new JAXBElement<String>(_TaskItemParametersDurationValue_QNAME, String.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "service.views", name = "fullname", scope = TaskItem.class)
    public JAXBElement<String> createTaskItemFullname(String value) {
        return new JAXBElement<String>(_TaskItemFullname_QNAME, String.class, TaskItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaskItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tns", name = "upDateTaskItemsResult", scope = UpDateTaskItemsResponse.class)
    public JAXBElement<TaskItem> createUpDateTaskItemsResponseUpDateTaskItemsResult(TaskItem value) {
        return new JAXBElement<TaskItem>(_UpDateTaskItemsResponseUpDateTaskItemsResult_QNAME, TaskItem.class, UpDateTaskItemsResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tns", name = "nd", scope = UpDateTaskItems.class)
    public JAXBElement<String> createUpDateTaskItemsNd(String value) {
        return new JAXBElement<String>(_UpDateTaskItemsNd_QNAME, String.class, UpDateTaskItems.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tns", name = "status", scope = UpDateTaskItems.class)
    public JAXBElement<String> createUpDateTaskItemsStatus(String value) {
        return new JAXBElement<String>(_UpDateTaskItemsStatus_QNAME, String.class, UpDateTaskItems.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tns", name = "gmd_request_id", scope = UpDateTaskItems.class)
    public JAXBElement<BigInteger> createUpDateTaskItemsGmdRequestId(BigInteger value) {
        return new JAXBElement<BigInteger>(_UpDateTaskItemsGmdRequestId_QNAME, BigInteger.class, UpDateTaskItems.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaskItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tns", name = "getTaskItemsDetailsResult", scope = GetTaskItemsDetailsResponse.class)
    public JAXBElement<TaskItem> createGetTaskItemsDetailsResponseGetTaskItemsDetailsResult(TaskItem value) {
        return new JAXBElement<TaskItem>(_GetTaskItemsDetailsResponseGetTaskItemsDetailsResult_QNAME, TaskItem.class, GetTaskItemsDetailsResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tns", name = "nd", scope = GetTaskItemsDetails.class)
    public JAXBElement<String> createGetTaskItemsDetailsNd(String value) {
        return new JAXBElement<String>(_UpDateTaskItemsNd_QNAME, String.class, GetTaskItemsDetails.class, value);
    }

}
