//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.16 at 04:05:57 PM CEST 
//


package com.fl.massengineprocessor.ws.skeleton;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TaskItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaskItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="co_id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="updated_at" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="process_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="failure_reason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="parameters_debit_value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="custumer_exernal_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gmd_request_id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="gmd_reauest_status" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="imsi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="msisdn" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="task_items_market" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rate_plan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="maap_task" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="created_at" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="error_message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="formule" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="parameters_duration_value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fullname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskItem", namespace = "service.views", propOrder = {
    "coId",
    "updatedAt",
    "processDate",
    "failureReason",
    "parametersDebitValue",
    "custumerExernalId",
    "gmdRequestId",
    "gmdReauestStatus",
    "imsi",
    "status",
    "msisdn",
    "taskItemsMarket",
    "ratePlan",
    "maapTask",
    "createdAt",
    "errorMessage",
    "formule",
    "parametersDurationValue",
    "fullname"
})
public class TaskItem {

    @XmlElementRef(name = "co_id", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<BigInteger> coId;
    @XmlElementRef(name = "updated_at", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> updatedAt;
    @XmlElementRef(name = "process_date", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> processDate;
    @XmlElementRef(name = "failure_reason", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<String> failureReason;
    @XmlElementRef(name = "parameters_debit_value", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<String> parametersDebitValue;
    @XmlElementRef(name = "custumer_exernal_id", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<String> custumerExernalId;
    @XmlElementRef(name = "gmd_request_id", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<BigInteger> gmdRequestId;
    @XmlElementRef(name = "gmd_reauest_status", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<BigInteger> gmdReauestStatus;
    @XmlElementRef(name = "imsi", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<String> imsi;
    @XmlElementRef(name = "status", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<String> status;
    @XmlElementRef(name = "msisdn", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<BigInteger> msisdn;
    @XmlElementRef(name = "task_items_market", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<String> taskItemsMarket;
    @XmlElementRef(name = "rate_plan", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ratePlan;
    @XmlElementRef(name = "maap_task", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<BigInteger> maapTask;
    @XmlElementRef(name = "created_at", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> createdAt;
    @XmlElementRef(name = "error_message", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<String> errorMessage;
    @XmlElementRef(name = "formule", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<String> formule;
    @XmlElementRef(name = "parameters_duration_value", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<String> parametersDurationValue;
    @XmlElementRef(name = "fullname", namespace = "service.views", type = JAXBElement.class, required = false)
    protected JAXBElement<String> fullname;

    /**
     * Gets the value of the coId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *     
     */
    public JAXBElement<BigInteger> getCoId() {
        return coId;
    }

    /**
     * Sets the value of the coId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *     
     */
    public void setCoId(JAXBElement<BigInteger> value) {
        this.coId = value;
    }

    /**
     * Gets the value of the updatedAt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the value of the updatedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setUpdatedAt(JAXBElement<XMLGregorianCalendar> value) {
        this.updatedAt = value;
    }

    /**
     * Gets the value of the processDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getProcessDate() {
        return processDate;
    }

    /**
     * Sets the value of the processDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setProcessDate(JAXBElement<XMLGregorianCalendar> value) {
        this.processDate = value;
    }

    /**
     * Gets the value of the failureReason property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFailureReason() {
        return failureReason;
    }

    /**
     * Sets the value of the failureReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFailureReason(JAXBElement<String> value) {
        this.failureReason = value;
    }

    /**
     * Gets the value of the parametersDebitValue property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getParametersDebitValue() {
        return parametersDebitValue;
    }

    /**
     * Sets the value of the parametersDebitValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setParametersDebitValue(JAXBElement<String> value) {
        this.parametersDebitValue = value;
    }

    /**
     * Gets the value of the custumerExernalId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCustumerExernalId() {
        return custumerExernalId;
    }

    /**
     * Sets the value of the custumerExernalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCustumerExernalId(JAXBElement<String> value) {
        this.custumerExernalId = value;
    }

    /**
     * Gets the value of the gmdRequestId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *     
     */
    public JAXBElement<BigInteger> getGmdRequestId() {
        return gmdRequestId;
    }

    /**
     * Sets the value of the gmdRequestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *     
     */
    public void setGmdRequestId(JAXBElement<BigInteger> value) {
        this.gmdRequestId = value;
    }

    /**
     * Gets the value of the gmdReauestStatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *     
     */
    public JAXBElement<BigInteger> getGmdReauestStatus() {
        return gmdReauestStatus;
    }

    /**
     * Sets the value of the gmdReauestStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *     
     */
    public void setGmdReauestStatus(JAXBElement<BigInteger> value) {
        this.gmdReauestStatus = value;
    }

    /**
     * Gets the value of the imsi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getImsi() {
        return imsi;
    }

    /**
     * Sets the value of the imsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setImsi(JAXBElement<String> value) {
        this.imsi = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStatus(JAXBElement<String> value) {
        this.status = value;
    }

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *     
     */
    public JAXBElement<BigInteger> getMsisdn() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *     
     */
    public void setMsisdn(JAXBElement<BigInteger> value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the taskItemsMarket property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTaskItemsMarket() {
        return taskItemsMarket;
    }

    /**
     * Sets the value of the taskItemsMarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTaskItemsMarket(JAXBElement<String> value) {
        this.taskItemsMarket = value;
    }

    /**
     * Gets the value of the ratePlan property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRatePlan() {
        return ratePlan;
    }

    /**
     * Sets the value of the ratePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRatePlan(JAXBElement<String> value) {
        this.ratePlan = value;
    }

    /**
     * Gets the value of the maapTask property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *     
     */
    public JAXBElement<BigInteger> getMaapTask() {
        return maapTask;
    }

    /**
     * Sets the value of the maapTask property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *     
     */
    public void setMaapTask(JAXBElement<BigInteger> value) {
        this.maapTask = value;
    }

    /**
     * Gets the value of the createdAt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the value of the createdAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setCreatedAt(JAXBElement<XMLGregorianCalendar> value) {
        this.createdAt = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setErrorMessage(JAXBElement<String> value) {
        this.errorMessage = value;
    }

    /**
     * Gets the value of the formule property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFormule() {
        return formule;
    }

    /**
     * Sets the value of the formule property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFormule(JAXBElement<String> value) {
        this.formule = value;
    }

    /**
     * Gets the value of the parametersDurationValue property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getParametersDurationValue() {
        return parametersDurationValue;
    }

    /**
     * Sets the value of the parametersDurationValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setParametersDurationValue(JAXBElement<String> value) {
        this.parametersDurationValue = value;
    }

    /**
     * Gets the value of the fullname property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFullname() {
        return fullname;
    }

    /**
     * Sets the value of the fullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFullname(JAXBElement<String> value) {
        this.fullname = value;
    }

}
