//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.10 at 11:31:40 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bean.ws.massengineprocessor.fl.com/")
package com.fl.massengineprocessor.ws.bean;
